Repository jenkinsci/git-server-plugin, pull requests merged in 2022-07, with the labels that each got.

#87 Use `instance-identity` as a plugin rather than a module
  .mvn/extensions.xml
  Jenkinsfile
  pom.xml
Labels: dependencies

#71 Make a comment more inclusive
  src/main/java/org/jenkinsci/plugins/gitserver/FileBackedHttpGitRepository.java
Labels: chore

#59 Correct capitalization in plugin name
  pom.xml
Labels: documentation

#88 Enable CD
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .mvn/maven.config
  pom.xml
Labels: chore
